// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFijU36Jtn7CNww0rfuj-1CP6Mtds8cIM',
    appId: '1:224751925440:web:69a34c4fb2139634a49525',
    messagingSenderId: '224751925440',
    projectId: 'studysmart-7d930',
    authDomain: 'studysmart-7d930.firebaseapp.com',
    storageBucket: 'studysmart-7d930.appspot.com',
    measurementId: 'G-3Z1MHNRRJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Ms09KsGYL0sdoRUVGHR_VQLMdpYYn3Y',
    appId: '1:224751925440:android:8fb90ecbb46662fea49525',
    messagingSenderId: '224751925440',
    projectId: 'studysmart-7d930',
    storageBucket: 'studysmart-7d930.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzW3DKXiTbwd80fzkVka1ZCQCxTMgbl-k',
    appId: '1:224751925440:ios:e86090913df35f8ca49525',
    messagingSenderId: '224751925440',
    projectId: 'studysmart-7d930',
    storageBucket: 'studysmart-7d930.appspot.com',
    iosBundleId: 'com.example.studySmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzW3DKXiTbwd80fzkVka1ZCQCxTMgbl-k',
    appId: '1:224751925440:ios:e86090913df35f8ca49525',
    messagingSenderId: '224751925440',
    projectId: 'studysmart-7d930',
    storageBucket: 'studysmart-7d930.appspot.com',
    iosBundleId: 'com.example.studySmart',
  );
}
